// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_01f7EFANGOtj6J7GhL4B7oAeUL_qeoM',
    appId: '1:773473561407:web:c298b6011595548de5418a',
    messagingSenderId: '773473561407',
    projectId: 'study-app-dab6f',
    authDomain: 'study-app-dab6f.firebaseapp.com',
    storageBucket: 'study-app-dab6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSyhACSqm7ZF8_H2u-ZcBmWzTmGPUDqDs',
    appId: '1:773473561407:android:0e4c95fb0fdb1f9be5418a',
    messagingSenderId: '773473561407',
    projectId: 'study-app-dab6f',
    storageBucket: 'study-app-dab6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3EulRaTkO1UkiF99reLm-i-SJgXSCM0',
    appId: '1:773473561407:ios:5499583f90ee8bb2e5418a',
    messagingSenderId: '773473561407',
    projectId: 'study-app-dab6f',
    storageBucket: 'study-app-dab6f.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3EulRaTkO1UkiF99reLm-i-SJgXSCM0',
    appId: '1:773473561407:ios:5499583f90ee8bb2e5418a',
    messagingSenderId: '773473561407',
    projectId: 'study-app-dab6f',
    storageBucket: 'study-app-dab6f.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_01f7EFANGOtj6J7GhL4B7oAeUL_qeoM',
    appId: '1:773473561407:web:6ae36522be15c4e1e5418a',
    messagingSenderId: '773473561407',
    projectId: 'study-app-dab6f',
    authDomain: 'study-app-dab6f.firebaseapp.com',
    storageBucket: 'study-app-dab6f.appspot.com',
  );

}